# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 2, size: 0.7, name: 'tag_2'}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'tag_mania'
      layout:
        [
          {id: 0,  size: 0.075,  x:  0.0  , y:  0.175, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 1,  size: 0.075,  x: -0.329, y:  0.04 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 3,  size: 0.075,  x:  0.165, y: -0.10 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 4,  size: 0.075,  x:  0.0  , y:  0.0  , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 5,  size: 0.075,  x: -0.135, y: -0.10 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 6,  size: 0.075,  x:  0.348, y:  0.04 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 7,  size: 0.0643, x: -0.348, y: -0.12 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 8,  size: 0.0643, x: -0.158, y:  0.198, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 9,  size: 0.0643, x:  0.14 , y:  0.04 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 10, size: 0.0643, x:  0.357, y:  0.198, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 11, size: 0.0643, x: -0.158, y:  0.04 , z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 12, size: 0.0643, x:  0.357, y: -0.123, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 13, size: 0.0643, x:  0.14 , y:  0.198, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707},
          {id: 14, size: 0.0643, x: -0.348, y:  0.198, z: 0.0, qw: -0.707, qx: 0.0, qy: 0.0, qz: 0.707}
        ]
    }
  ]
